// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqztSIwLQhCHzQNmCzX6qdgFFHCFrf-nc',
    appId: '1:196875595307:web:cb575ca147af01f59b446e',
    messagingSenderId: '196875595307',
    projectId: 'rulr-matrimony',
    authDomain: 'rulr-matrimony.firebaseapp.com',
    storageBucket: 'rulr-matrimony.appspot.com',
    measurementId: 'G-4SBF28MMWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAF3Fm7SlwwsvqMVatfOud5m36Zd4UIw',
    appId: '1:196875595307:android:5101792b89db8b0c9b446e',
    messagingSenderId: '196875595307',
    projectId: 'rulr-matrimony',
    storageBucket: 'rulr-matrimony.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgl7qIRuVxtMbEIeN3XVEkrtGC5_MMWL4',
    appId: '1:196875595307:ios:66b2299ba52407bd9b446e',
    messagingSenderId: '196875595307',
    projectId: 'rulr-matrimony',
    storageBucket: 'rulr-matrimony.appspot.com',
    iosBundleId: 'com.example.matrimonyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgl7qIRuVxtMbEIeN3XVEkrtGC5_MMWL4',
    appId: '1:196875595307:ios:66b2299ba52407bd9b446e',
    messagingSenderId: '196875595307',
    projectId: 'rulr-matrimony',
    storageBucket: 'rulr-matrimony.appspot.com',
    iosBundleId: 'com.example.matrimonyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqztSIwLQhCHzQNmCzX6qdgFFHCFrf-nc',
    appId: '1:196875595307:web:03b4a1ec001ddaf69b446e',
    messagingSenderId: '196875595307',
    projectId: 'rulr-matrimony',
    authDomain: 'rulr-matrimony.firebaseapp.com',
    storageBucket: 'rulr-matrimony.appspot.com',
    measurementId: 'G-57VMFX8ZX9',
  );
}
